### ISSUE TITLE
Feral Flash Intermittent

### ISSUE THREAD

**Issue by sonick42** [AdiAddons/AdiButtonAuras#184]
Flash at 5 combo point for ferals isn't working properly. It has always worked great for the most part but since yesterday it's not working when you start a fight from stealth and only working about half of the time when you don't start the fight from stealth. I deleted and reinstall the addon, not sure what's going on.

**Comment by Rainrider** [comment]
Since there are absolutely no changes done to the addon recently and also no api changes, I can't see how something can stop working all of a sudden. Reinstalling the addon does not change anything in your settings, so if you have any custom rules or changed settings, you maybe done something wrong there. Please have a look and verify if the issue still persists.

**Comment by sonick42** [comment]
I have tried reinstalling as well as resetting all settings to default and
it still is only working about ince every 3 or 4 pulls. I have also tried
clearing my wtf folder as well as disabling all other addons.

**Comment by Rainrider** [comment]
Ok, I can reproduce this. It seems related to paging and it only applies to the animation and not the stack count color. I'll investigate further. A workaround for the time being is to place the finishing moves so that they are visible when a combo point is applied. From then on one can change pages as long as combat is not toggled.

**Comment by sonick42** [comment]
I think also part of the problem may be stealth. The only time I can get it
to work is when I enter combat without stealth. As soon as I hit
Incarnation which makes abilities act as if I was stealthed it stops
working again. Thanks for the help and thanks for the addon. This is the
main addon I use and I literally cant play without it. Its great!

**Comment by Rainrider** [comment]
Stealth seems to be involved only if it causes action bar paging. Btw prowl does not invoke paging with the default ui, I also can't reproduce your results with Incarnation. What action bar addon are you using?

**Comment by sonick42** [comment]
Oh I am using bartender. I would think prowl would cause paging even in the
default ui since your action bar is different when stealthed as opposed to
not stealthed.

**Comment by Rainrider** [comment]
Nope, default ui is the same page as the cat form page. This will take me some time probably, please be patient.

**Comment by sonick42** [comment]
Oh ok gotcha. No problem man take your time. I set up weakauras to flash my
finishers at 5 combo points for now but am still using adibuttons for my
bleed timers. I do prefer to use aba for all of it though so I will
definitely be looking forward to a fix. Thanks again!

Sonick US-Stormrage
