### ISSUE TITLE
Why does this Mastery weapon enchant rule not work?

### ISSUE THREAD

**Issue by arcadepro** [AdiAddons/AdiButtonAuras#199]
```
return Configure {
        "Mark of Bleeding Hollow",
        L["Mark of Bleeding Hollow"],
        "12294", -- Mortal Strike
        "player",
        "UNIT_AURA",
        function(_, model)
            if GetPlayerBuff("player", 173322) then
                model.highlight = "good"
            end
        end,
    }
```

Is it a libitembuffs issue?

**Comment by Rainrider** [comment]
There is a difference between 12294 and "12294".

**Comment by Rainrider** [comment]
Btw this is a just a guess. Lua supports coersion, so this would normally not be an issue but since ABA expects either a table or a number I think we are picky about the exact type of the passed value. We do use "item:<itemid>" for items though, so maybe that causes the problem. Just try it that way and tell me the result. I'm writing this from my phone and the response is from the top of my head. Haven't looked at ABA's code for some time

**Comment by arcadepro** [comment]
I don't think thats the issue because
    return Configure {
            "Blast Furnace Door",
            L["Blast Furnace Door Buff."],
            "6572", -- revenge
            "player",
            "UNIT_AURA",
            function(_, model)
                if GetPlayerBuff("player", 177056) then
                    model.highlight = "good"
                end
            end,
        }

Works. 

I feel like the Bleeding Hollow Enchant just isn't recognized. It certainly isn't in libitembuffs.

**Comment by Rainrider** [comment]
I don't see why it should be in LIB. If the IDs are correct, it should work like it is.

**Comment by Rainrider** [comment]
I can reproduce your results with buffs that don't have a caster (the 8th return of UnitAura is nil). Don't know if this is the causing the issue, this is probably something @Adirelle has to look at.

**Comment by arcadepro** [comment]
Ok, thanks for the replies.
