### ISSUE TITLE
Spells & Items Broken

### ISSUE THREAD

**Issue by sonick42** [AdiAddons/AdiButtonAuras#210]
Just updated. Been waiting for this update and this addon is crucial to my UI. The Spells & Items tab shows in config but I can't enable it. Basically what I use this addon for is to track my bleeds on my action bar icons. I use the counter on it so I know when I need to refresh.

Any help would be appreciated.
![adb](https://cloud.githubusercontent.com/assets/12499639/16964755/1fdbbf58-4dcb-11e6-95f6-4ae4c5c9ce35.png)

**Comment by Rainrider** [comment]
You are using the last wod version probably in the US. I made the tag so that people can tell versions apart since the Legion pre-patch comes tomorrow in Europe and I don't know when in the rest of the world.

I pushed a working beta for the pre-patch to curse, however it will take some time to appear. By working I mean not throwing errors. A lot of class data is still missing however. You can track progress in #209 and AdiAddons/LibPlayerSpells-1.0#82. Druid is sadly among the classes with missing data and adding it is a lengthy process, please be patient.

**Comment by sonick42** [comment]
Alright thanks. If there is any data you need on feral please let me know
and I cna get it for you.

**Comment by Rainrider** [comment]
Guardian and feral druids are now included in LibPlayerSpells. Just grab an alpha from [wowace](http://www.wowace.com/addons/libplayerspells-1-0/) and install like any other addon.

Combo points display on spenders is still not re-implemented. You can either make a custom rule for it or wait until I get to it.

Also keep in mind that some abilities have multiple auras associated with them. Since LibPlayerSpells is meant to provide information about those associations, they are all listed there. This leads to some visual pollution in ABA and the rules for it will be updated at a later time. For now you can deactivate the rules for auras you don't want to track in ABA.

**Comment by sonick42** [comment]
Awesome thx!
