### ISSUE TITLE
Is there a simple way to hide stacks on a given spell?

### ISSUE THREAD

**Issue by arcadepro** [AdiAddons/AdiButtonAuras#229]
Or does it require making a rule to handle the entire spell? I guess this is a similar issue as #30. from 2014.
I'm just looking for an easy way to hide the stack count on Agony (Warlock). 

More generally, perhaps each spell that can stack should have an option to _not_ show them?

As a quick workaround I'm excluding Agony from the import and using this quickly bodged together rule. It excludes the stacks and flashes when you need to refresh.

```		
Configure {
			"RefreshAgony",
			format(
				L["%s when your debuff %s should be refreshed on %s."],
				DescribeHighlight("hint"), -- hint or flash
				GetSpellInfo(980),          -- Agony
				DescribeAllTokens("enemy")  -- enemy string
			),
			980, -- Agony
			"enemy",
			{ "UNIT_AURA", "UNIT_COMBAT" }, -- fast enough to be usable
			function(units, model)
				local found, count, expiration = GetPlayerDebuff(units.enemy, 980)
				local Duration = 18
				local refreshWindow = Duration * 0.25
				if found then
					model.highlight = "bad"
					model.expiration = expiration
					if expiration - GetTime() < refreshWindow then
						model.hint = true
					end
				end
			end,
			980, -- Agony
		},
```

There was a typo in the Burning Rush rule that I noticed too. ARUA vs. AURA Iirc.

**Comment by Rainrider** [comment]
The short answer is: no

You could disable the default rule and add a custom one as you did (you don't need to edit any files for that.

ABA has no special knowledge about which auras can stack. It just checks the returns of UnitAura and updates the model properties accordingly. I could take a look after I'm back from vacation, but this is not a high priority for me, since for your use case you will still have to create your custom rule to use the refresh window.

Thanks for spotting the typo.

**Comment by Rainrider** [comment]
I'll close this and leave #30 open as it is the same topic.
