### ISSUE TITLE
Protection Paladin: Blessed Stalwart | Marksmanship Hunter: Trick Shot

### ISSUE THREAD

**Issue by ividyon** [AdiAddons/AdiButtonAuras#265]
Opening a report about two buffs that are tracked via AdiButtonAuras, which I think shouldn't be.

If this is something I can manually do in the options, please forgive me. The "hardcoded" part of the addon description made me assume otherwise, and I didn't find how to do it.

----

# Shield of the Righteous / Blessed Stalwart

Shield of the Righteous is a Protection Paladin skill that reduces damage taken by ~50%. Its uptime is very vital to track, and AdiButtonAuras tracks it, which is great.

However, when it's not up, instead the button for SotR will track the Artifact Trait buff Blessed Stalwart. This is a tiny 8% buff to SotR, which will *usually* be up anyway.

On the SotR button, it shares the same space with the SotR uptime. This can be highly misleading; you look at the button, see that there's 6 seconds remaining, and think you're safe for another 6 seconds; however, that's just the Blessed Stalwart buff.

Can we untrack Blessed Stalwart on the Shield of the Righteous button?

----

# Aimed Shot / Trick Shot
Same story for Marksmanship hunters:

The rotation of Marksmanship revolves around applying the "Vulnerable" debuff to targets, which increases damage taken by Aimed Shot.

AdiButtonAuras tracks this "Vulnerable" debuff with a number on the Aimed Shot icon. However, it also tracks the talent Trick Shot in the same icon, which increases Aimed Shot damage by 15% and is *also* up most of the time, and its not important enough to keep track of.

Can we untrack Trick Shot on the Aimed Shot button?

----

# Spell IDs etc.

Shield of the Righteous spell: 53600 http://www.wowhead.com/spell=53600/shield-of-the-righteous
Shield of the Righteous buff: 132403 http://www.wowhead.com/spell=132403/shield-of-the-righteous#buff
Blessed Stalwart artifact trait: 238133 http://www.wowhead.com/spell=238133/blessed-stalwart
Blessed Stalwart buff: 242869 http://www.wowhead.com/spell=242869/blessed-stalwart

Aimed Shot spell: 19434 http://www.wowhead.com/spell=19434/aimed-shot
Vulnerable debuff: 187131 http://www.wowhead.com/spell=187131/vulnerable
Trick Shot talent: 199522 http://www.wowhead.com/spell=199522/trick-shot

**Comment by Rainrider** [comment]
This will require a somewhat lengthy explanation of how the rules are built and why. For a TL;DR version just take a look at the screenshot below.

ABA gets information about spell dependencies from LibPlayerSpells-1.0 (LPS). LPS aims to list all possible ability relations and ABA just serves as a display for that with some customization and the bundling of other utilities on top of it. While ABA has a built-in ability to exclude some of the spells from LPS, I'd rather leave this to the user. The reason is that I can't know every spec for every class in the game and even then it would be difficult to consider all possible combinations of spec/talents/honor talents/artifacts/legendaries and what not. I also don't want to impose my (or someone else's) understanding of how it should be done on every user of the addon. So the best solution that comes to mind is to let the user customize which rules are active. This boils down to the following steps:

  1. Type `/aba` in chat to open the options panel
  2. Select `Spells & items` from the menu list
  3. Click on the ability on your action bar you want to customize (spells with active rules have a green overlay, spells with only inactive rules have a red overlay, no overlay = no known rules)
  4. From the rules list that appears, deselect the rules you don't like or consider unimportant

![wowscrnshot_011518_143010](https://user-images.githubusercontent.com/363876/34945581-2450a152-fa04-11e7-98e5-47ab5d5a88ae.jpg)

If you need an even finer control over the rules, you could build custom user rules too. For this take a look at the documentation.

**Comment by ividyon** [comment]
Thank you! I had difficulties finding how to edit the spell rules because the "Spells & Events" tab was empty. It took me a while to look down at my action bars and realize they're all glowing green!

I disabled the rules for myself, and that is all I could possibly want to ask for. Thank you for your great addon! That'll be all.
