### ISSUE TITLE
Suggestion: Hide countdown text

### ISSUE THREAD

**Issue by mspykerez** [AdiAddons/AdiButtonAuras#268]
Is it possible to by default ''show the good border when a buff is found on yourself'' but do NOT show the countdown text?

**Comment by Rainrider** [comment]
![wowscrnshot_021618_232727](https://user-images.githubusercontent.com/363876/36332113-28bf0086-1371-11e8-8560-d7c89720a3c5.jpg)

**Comment by Rainrider** [comment]
For the countdown text, I'd rather keep it as a global setting instead of a per spell one. I would like to avoid issues like "countdown text is broken cos it works on all my buttons but not on this one" and I fail to see a particular benefit from implementing it. Also, it would then be better to move all countdown related options from global to per spell, which will open the possibility for even more clutter. I think ABA benefits from the visual consistency it has now and in general consistent looks are easier and faster to process visually.

As for Roll the Bones, the rule for it is generated automatically. You can however achieve what you need by creating a custom rule and deactivating the default one.
