### ISSUE TITLE
Missing Steady Shot debuff

### ISSUE THREAD

**Issue by BanditBanditBandit** [AdiAddons/AdiButtonAuras#302]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.0.21-1-g2ba56fa

#### How did you install the addon (twitch client/manually)?
twitch client

#### If using the twitch client, what type of release did you install (alpha/beta/release)?
alpha

#### If your report is about a missing or wrong spell provide the following information:
  - Your class:Hunter
  - Your spec:Marksman
  - Name of the spell (and spell id if known):277959
  - Source of the spell (core ability/talent/pvp):56641
  - Do you use a macro to cast the spell (post the macro if so):
#showtooltip Steady Shot
/cleartarget [noharm]
/startattack
/cast [exists] Steady Shot

**Comment by Rainrider** [comment]
Azerite traits won't be included through LibPlayerSpells/AdiButtonAuras as it was the case with legendaries in Legion. I simply lack the time to add and verify the spell ids for all specs. You can write yourself a custom rule for this.

I plan to support the ability to tell if a given azerite spell is active for the character so that they can be used as providers for custom rules, however this will take some time due to time constrains too. The downside is that custom rules for azerite spells will be active whole the time instead of only when the spell is known.

**Comment by BanditBanditBandit** [comment]
I tried adding a custom rule for a debuff and had a very difficult time. After 20 minutes of futsing around I gave up, the article linked in the sample could use some more explanation. Maybe change the sample to something more useful, a simple buff or debuff code would be much more helpful to most people.

**Comment by Rainrider** [comment]
```lua
return SelfBuffAliases {
    56641, -- on Steady Shot
    277959, -- show Steady Aim
}
```
The parts after the double dashes are comments. This is basically the first example in the documentation, just using `SelfBuffAliases` instead of `BuffAliases`, because Steady Aim is a self buff.

`Configure` is the only rule where you need to provide events (you can see this by looking at the list of arguments the rule takes). All other rules are internally translated to a `Configure` rule, but you should not be concerned by that.

You can take a look at the [class files in the rules folder](https://github.com/AdiAddons/AdiButtonAuras/tree/master/rules), they all follow the syntax for user rules. Don't edit anything there though as it will be overwritten the next time you update the addon. User rules written through the in-game config are persistent.
