### ISSUE TITLE
Countdown text position

### ISSUE THREAD

**Issue by monochrony** [AdiAddons/AdiButtonAuras#328]
#### Which version of AdiButtonAuras are you using (enter the exact version number here)?
2.2.0

#### How did you install the addon (twitch client/manually)?
manually

#### If you installed manually, where did you download the addon from?
Curse/Twitch

#### Which type of installation did you choose (nolib/normal)?
normal

The countdown text on a spell is not affected by the text position offest. This is a problem, because the spell I want to show a buff on (Demonology Warlock - Spell: Implosion (196277)) also shows me Imp stacks provided by the Blizzard UI. The countdown will obfuscate the Imp stack count, making it hard to read.

Edit: Also, is there an event to draw the current amount of Imps from? _SPELL_UPDATE_CHARGES_ doesn't work. I'd like to create a rule to make Implosion flash whenever I have 3 or more Imps out with the buff "Explosive Potential" missing.

**Comment by Rainrider** [comment]
![implosion](https://user-images.githubusercontent.com/363876/61138119-1dfbd000-a4c7-11e9-8b96-28cc2b65b805.gif)
The countdown text IS affected by the text position offset. The COUNT text is not effected if it is the default count text (see count text for Hand of Gul'dan on the left and compare to the stock ui count on Implosion). If a rule sets a count and it differs from the stock display, ABA count is placed in the middle of the button (it makes it a bit cramped on small buttons but normally both are visible in this case).

Currently you can track the imp count only through the combat log, which is out of scope for ABA.

**Comment by monochrony** [comment]
X Offset -5, you can see it working on Demonic Core, 
yet the buff countdown on Implosion is still centered:

![Countdown on Implosion](https://i.imgur.com/vbm8gH8.png)

`SelfBuffAliases {196277, 275398, 275395}`

**Comment by Rainrider** [comment]
This is because of how text positioning is currently implemented. The text box is spanned between the left and right sides of the button. Positive x offsets makes this box shrink, negative ones make it grow. There are two text indicators - countdown and count. If only one is shown, it is placed in the middle of the text box, which is always the middle of the button. If both are shown, then countdown is on the left and the count is on the right. Normally this takes the default count text into account (however it will only work reliably only for real spell charges, as there is an in-game event for that, so ABA could react and update the display)

On your screenshot on the left in the upper row is the rule for Demonic Core on Demonbolt, which has stacks, which are represented by the count text indicator. This is why the countdown appears on the left of the button.

Technically, this is easy to fix:
1. Either make the text box move with the x offset (instead of shrinking and growing)
2. Or keep current x offset behavior and always place the countdown indicator on the left.

However there are downsides:
For 1: Depending on your settings, it is possible for one text indicator to appear over the next or previous button, which makes it hard to tell which is which. Also, having the one indicator inside and the other on the border or outside is inconsistent. This is the reason for the current implementation.

For 2: Most auras do not have stacks, meaning the countdown is the only display most of the time. Having it centered makes it easier to process and is visually more appealing because of symmetry (equal amount of empty space on both sides) and because the borders are not too close to the text. Making the countdown text left aligned would push people to increase the x offset leading to more cramped display when both count and countdown are shown. Also this would change a behavior which ABA had since the beginning.

What do you think?
