### ISSUE TITLE
CAN ANYONE TAKE THIS ON AND FIX IT OR IS THEIR ANOTHER ADDON LIKE THIS AROUND?

### ISSUE THREAD

**Issue by xapollyon** [AdiAddons/AdiButtonAuras#407]
CAN ANYONE TAKE THIS ON AND FIX IT OR IS THEIR ANOTHER ADDON LIKE THIS AROUND?

**Comment by SlivaNilow** [comment]
https://www.curseforge.com/wow/addons/litebuttonauras

**Comment by Ukhai** [comment]
Keep in mind that author has/will eventually hit the same problems adibuttonauras had. It really is up to the community to help keep these updated,

I'm very slowly learning LUA but it's a daunting task while wanting to play the game at the same time.

**Comment by mbattersby** [comment]
Hello. I hate to intrude on someone else's comments, but I am the author of the linked addon LiteButtonAuras and I wanted to clarify two things.

1. It is not at all a complete replacement for AdiButtonAuras. It really only does about 1/4 of the things, and I have no intention of making it do more. You can see the page for what it does, but it doesn't do power points (chi, holy power, etc), doesn't suggest spells (except for interrupt and soothe), doesn't handle `@unit` in macros, has no GUI, etc.
2. LiteButtonAuras was written with the specific goal of being easy to maintain, that's why it matches auras by name and not with a library of spell IDs that must be manually updated. It can certainly get out of date, but it is very small (1500 lines of code), and I think any decent addon programmer could update it quickly if I got hit by a bus.

I hope someone does resurrect AdiButtonAuras. It is (was?) a terrific addon and deserves a new life.
